C:\_mydocuments\srcfebr2024b\cplmsc\appwiz.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\azman.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\bthprops.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\certlm.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\certmgr.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\comexp.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\compmgmt.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\Data61x4_2_2.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\Data9377_2_0.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\desk.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\devmgmt.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\DevModeRunAsUserConfig.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\diskmgmt.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\eventvwr.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\file.bat
C:\_mydocuments\srcfebr2024b\cplmsc\Firewall.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\fsmgmt.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\gpedit.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\hdwwiz.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\inetcpl.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\intl.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\irprops.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\joy.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\lusrmgr.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\main.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\mmsys.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\ncpa.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\perfmon.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\powercfg.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\printmanagement.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\rsop.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\sapi.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\secpol.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\services.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\sysdm.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\TabletPC.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\taskschd.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\telephon.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\timedate.cpl - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\tpm.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\WF.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\WmiMgmt.msc - Shortcut.lnk
C:\_mydocuments\srcfebr2024b\cplmsc\wscui.cpl - Shortcut.lnk
